### ISSUE TITLE
Compile on Catalina HELP

### ISSUE THREAD

**Issue by ghost** [lostjared/acidcamGL#1]
Hello,

I would like to do the filter on the camera so people can see it not on desktop how can i do it?
But I am trying to compile it and it failed please see it and advise how can I continue from here?

I followed the youtube video in your channel
the error is after `mkdir build; cd build` then ran `cmake ..` complains on OpenCV

```

-- Build configuration is: Release
-- is the C++ compiler loaded? 1
-- The C++ Compiler ID is: AppleClang
-- The C++ Compiler Version: 11.0.3.11030032
CMake Error at CMakeLists.txt:98 (find_package):
  By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "OpenCV", but
  CMake did not find one.

  Could not find a package configuration file provided by "OpenCV" with any
  of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

  Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
  "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
```

Attached file of error: 
[logs.zip](https://github.com/lostjared/acidcamGL/files/5491436/logs.zip)

thank you in adanved

**Comment by ghost** [comment]
I literally ran brew install and it didn't opencv and after an hour I tried, then.. now it works.

Is there any instructions to do that video into my camera?
https://www.youtube.com/watch?v=LYA5pGKdNIM

**Comment by ghost** [comment]
Not work..
Getting error, after compiling for `acidcamGL` :( 
```
[ 11%] Linking CXX executable acidcamGL
Undefined symbols for architecture x86_64:
  "acidcam::StereoCam::Load(int*)", referenced from:
      _main in main.cpp.o
  "acidcam::StereoCam::Render(cv::Mat&)", referenced from:
      acidcam::AcidCam_Window::update(double) in main.cpp.o
      acidcam::AcidCam_Window::CallCustom(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, cv::Mat&) in main.cpp.o
  "acidcam::StereoCam::StereoCam()", referenced from:
      acidcam::AcidCam_Window::AcidCam_Window() in main.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [acidcamGL] Error 1
make[1]: *** [CMakeFiles/acidcamGL.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by lostjared** [comment]
I was unable to finish the stereo cam as I am I. The hospital I was in a coma.I have pralysis and have to learn to walk and type again. When I get out of the hospital I’ll update the code. Try an older revision without the stereo cam.

**Comment by ghost** [comment]
> I was unable to finish the stereo cam as I am I. The hospital I was in a coma.I have pralysis and have to learn to walk and type again. When I get out of the hospital I’ll update the code. Try an older revision without the stereo cam.

I'm sorry to hear, I hope you are doing okay. I don't know how to do it very bad this stuff :( ..
edit: got it! i compiled this https://github.com/lostjared/acidcamGL/releases/tag/v1.0.003.x86_64


Do you know how to revert `sudo make install` ?

**Comment by lostjared** [comment]
I am back this issue is fixed.
